export const suburbs = [
  "Acacia Ridge",
  "Albany Creek",
  "Albion",
  "Alderley",
  "Alexandra Hills",
  "Algester",
  "Allingham",
  "Amberley",
  "Amity",
  "Amity Point",
  "Annerley",
  "Anstead",
  "Aquatic Paradise",
  "Arana Hills",
  "Archerfield",
  "Armstrong Creek",
  "Ascot",
  "Ashgrove",
  "Aspley",
  "Auchenflower",
  "Augustine Heights",
  "Bald Hills",
  "Balmoral",
  "Banksia Beach",
  "Banyo",
  "Bardon",
  "Barellan Point",
  "Basin Pocket",
  "Beachmere",
  "Bellara",
  "Bellbird Park",
  "Bellbowrie",
  "Bellmere",
  "Bellthorpe",
  "Belmont",
  "Berrinba",
  "Birkdale",
  "Blacksoil",
  "Blackstone",
  "Bongaree",
  "Boondall",
  "Booval",
  "Boronia Heights",
  "Bowen Hills",
  "Bracalba",
  "Bracken Ridge",
  "Brassall",
  "Bray Park",
  "Brendale",
  "Bridgeman Downs",
  "Brighton",
  "Brisbane (CBD)",
  "Brisbane Airport",
  "Brookfield",
  "Brookwater",
  "Browns Plains",
  "Buccan",
  "Bulimba",
  "Bulwer",
  "Bundamba",
  "Bunya",
  "Buranda",
  "Burbank",
  "Burpengary",
  "Burpengary East",
  "Caboolture",
  "Caboolture South",
  "Calamvale",
  "Calvert",
  "Camira",
  "Camp Hill",
  "Camp Mountain",
  "Campbells Pocket",
  "Cannon Hill",
  "Capalaba",
  "Capalaba West",
  "Carbrook",
  "Carina",
  "Carina Heights",
  "Carindale",
  "Carole Park",
  "Carseldine",
  "Cashmere",
  "Cedar Creek",
  "Cedar Creek",
  "Cedar Grove",
  "Cedar Vale",
  "Cedarton",
  "Chambers Flat",
  "Chandler",
  "Chapel Hill",
  "Charters Towers City",
  "Chelmer",
  "Chermside",
  "Chermside West",
  "Churchill",
  "Chuwar",
  "Clayfield",
  "Clear Mountain",
  "Cleveland",
  "Clontarf",
  "Clontarf Beach",
  "Closeburn",
  "Coalfalls",
  "Collingwood Park",
  "Commissioners Flat",
  "Coochiemudlo Island",
  "Coopers Plains",
  "Coorparoo",
  "Corinda",
  "Cornubia",
  "Cosgrove",
  "Cowan Cowan",
  "Crestmead",
  "D'aguilar",
  "Daisy Hill",
  "Dakabin",
  "Darra",
  "Dayboro",
  "Deagon",
  "Deception Bay",
  "Deebing Heights",
  "Delaneys Creek",
  "Dinmore",
  "Donnybrook",
  "Doolandella",
  "Draper",
  "Drewvale",
  "Dunwich",
  "Durack",
  "Dutton Park",
  "Eagle Farm",
  "East Brisbane",
  "East Ipswich",
  "Eastern Heights",
  "Eatons Hill",
  "Ebbw Vale",
  "Ebenezer",
  "Ecco Ripley",
  "Eight Mile Plains",
  "Elimbah",
  "Ellen Grove",
  "England Creek",
  "Enoggera",
  "Enoggera Reservoir",
  "Everton Hills",
  "Everton Park",
  "Fairfield",
  "Ferny Grove",
  "Ferny Hills",
  "Fig Tree Pocket",
  "Fitzgibbon",
  "Flinders View",
  "Forest Lake",
  "Forestdale",
  "Foritude Valley",
  "Fortitude Valley",
  "Gailes",
  "Gaythorne",
  "Geebung",
  "Godwin Beach",
  "Goodna",
  "Gordon Park",
  "Graceville",
  "Grandchester",
  "Grange",
  "Greenbank",
  "Greenslopes",
  "Griffin",
  "Gumdale",
  "Haigslea",
  "Hamilton",
  "Harrisville",
  "Hawthorne",
  "Heathwood",
  "Hemmant",
  "Hendra",
  "Heritage Park",
  "Herston",
  "Highgate Hill",
  "Highvale",
  "Hillcrest",
  "Holland Park",
  "Holland Park West",
  "Inala",
  "Indooroopilly",
  "Ipswich",
  "Ironbark",
  "Jamboree Heights",
  "Jimboomba",
  "Jindalee",
  "Jollys Lookout",
  "Joyner",
  "Kallangur",
  "Kangaroo Point",
  "Karalee",
  "Karana Downs",
  "Karawatha",
  "Karrabin",
  "Karragarra Island",
  "Kedron",
  "Kelvin Grove",
  "Kenmore",
  "Kenmore Hills",
  "Keperra",
  "Kholo",
  "King Scrub",
  "Kingston",
  "Kippa-ring",
  "Kobble Creek",
  "Kooringal",
  "Kuraby",
  "Kurwongbah",
  "Laceys Creek",
  "Lake Manchester",
  "Lamb Island",
  "Lanefield",
  "Larapinta",
  "Lawnton",
  "Leichhardt",
  "Loamside",
  "Logan Central",
  "Logan Reserve",
  "Logan Village",
  "Loganholme",
  "Loganlea",
  "Lota",
  "Lower Mount Walker",
  "Lutwyche",
  "Lytton",
  "Macgregor",
  "Mackenzie",
  "Macleay Island",
  "Mango Hill",
  "Manly",
  "Manly West",
  "Mansfield",
  "Marburg",
  "Margate",
  "Marsden",
  "McDowall",
  "Meadowbrook",
  "Meldale",
  "Middle Park",
  "Milton",
  "Mitchelton",
  "Moggill",
  "Moodlu",
  "Moores Pocket",
  "Moorina",
  "Moorooka",
  "Morayfield",
  "Moreton Bay",
  "Moreton Island",
  "Morningside",
  "Mount Coot-tha",
  "Mount Cotton",
  "Mount Crosby",
  "Mount Forbes",
  "Mount Glorious",
  "Mount Gravatt",
  "Mount Gravatt East",
  "Mount Mee",
  "Mount Nebo",
  "Mount Ommaney",
  "Mount Pleasant",
  "Mount Samson",
  "Muirlea",
  "Mundoolun",
  "Munruben",
  "Murarrie",
  "Murrumba Downs",
  "Mutdapilly",
  "Narangba",
  "Nathan",
  "Neurum",
  "New Beith",
  "New Chum",
  "New Farm",
  "Newmarket",
  "Newport",
  "Newstead",
  "Newtown",
  "Ningi",
  "Norman Park",
  "North Booval",
  "North Ipswich",
  "North Lakes",
  "North Maclean",
  "North Stradbroke Island",
  "North Tivoli",
  "Northgate",
  "Nudgee",
  "Nudgee Beach",
  "Nundah",
  "Ocean View",
  "One Mile",
  "Ormiston",
  "Oxley",
  "Paddington",
  "Pallara",
  "Park Ridge",
  "Park Ridge South",
  "Parkinson",
  "Peak Crossing",
  "Perulpa Island",
  "Petrie",
  "Petrie Qld",
  "Petrie Terrace",
  "Pine Mountain",
  "Pinjarra Hills",
  "Pinkenba",
  "Point Lookout",
  "Priestdale",
  "Pullenvale",
  "Purga",
  "Raby Bay",
  "Raceview",
  "Ransome",
  "Red Hill",
  "Redbank",
  "Redbank Plains",
  "Redcliffe",
  "Redland Bay",
  "Regents Park",
  "Richlands",
  "Ripley",
  "Ripley Valley",
  "Riverhills",
  "Riverview",
  "Robertson",
  "Rochedale",
  "Rochedale South",
  "Rocklea",
  "Rocksberg",
  "Rosewood",
  "Rothwell",
  "Runcorn",
  "Rush Creek",
  "Russell Island",
  "Sadliers Crossing",
  "Salisbury",
  "Samford Valley",
  "Samford Village",
  "Samsonvale",
  "Sandgate",
  "Sandstone Point",
  "Scarborough",
  "Seven Hills",
  "Seventeen Mile Rocks",
  "Shailer Park",
  "Sheldon",
  "Sherwood",
  "Shorncliffe",
  "Silkstone",
  "Sinnamon Park",
  "Slacks Creek",
  "South Brisbane",
  "South Maclean",
  "South Ripley",
  "Spring Hill",
  "Spring Mountain",
  "Springfield",
  "Springfield Lakes",
  "Springwood",
  "St Helena Island",
  "St Lucia",
  "Stafford",
  "Stafford Heights",
  "Stanmore",
  "Stockleigh",
  "Stones Corner",
  "Stony Creek",
  "Strathpine",
  "Stretton",
  "Sumner",
  "Sunnybank",
  "Sunnybank Hills",
  "Swanbank",
  "Taigum",
  "Tallegalla",
  "Tamborine",
  "Tamborine Village",
  "Tanah Merah",
  "Tangalooma",
  "Taringa",
  "Tarragindi",
  "Teneriffe",
  "Tennyson",
  "Thagoona",
  "The Gap",
  "Thorneside",
  "Thornlands",
  "Timberlands",
  "Tingalpa",
  "Tivoli",
  "Toombul",
  "Toorbul",
  "Toowong",
  "Unclassified Qld",
  "Underwood",
  "Upper Brookfield",
  "Upper Caboolture",
  "Upper Kedron",
  "Upper Mount Gravatt",
  "Victoria Point",
  "Virginia",
  "Wacol",
  "Wakerley",
  "Walloon",
  "Wamuran",
  "Wamuran Basin",
  "Warner",
  "Waterford West",
  "Wavell Heights",
  "Wellers Hill",
  "Wellington Point",
  "West End",
  "West Ipswich",
  "Westlake",
  "White Patch",
  "Whiteside",
  "Wights Mountain",
  "Willawong",
  "Willowbank",
  "Wilston",
  "Windsor",
  "Wishart",
  "Woodend",
  "Woodford",
  "Woodhill",
  "Woodridge",
  "Woody Point",
  "Woolloongabba",
  "Wooloowin",
  "Woolshed",
  "Woorim",
  "Wulkuraka",
  "Wynnum",
  "Wynnum West",
  "Yamanto",
  "Yarrabilba",
  "Yeerongpilly",
  "Yeronga",
  "Yugar",
  "Zillmere"
];
